server:
  port: 8989
  servlet:
    context-path: /store

spring:
  datasource:
   # driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_hibernate?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      ddl-auto: create-drop
      hdm2ddl.auto: create


  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html